### ISSUE TITLE
Create a generalized helper class

### ISSUE THREAD

**Issue by N0W0RK** [N0W0RK/TUM_GAD_Tests_SS21#48]
The idea is to build a helper class that eases the creation of large tests with simmilar inputs.
This issue tries to resolve the codestyle limitations discussed in [#47](https://github.com/N0W0RK/TUM_GAD_Tests_SS21/issues/47#issuecomment-855252169)

Goals:
- [x] Test symlink copatibility across systems.
- [ ] Offload Test Inputs and Outputs into structured text (e.g. JSON, XML, etc.).
- [ ] Create a general tester class that can be used for every exercise.

**Comment by CrsiX** [comment]
Design decisions we have to make:

- Is this generalized class part of every exercise (basically a copy & paste thing or using symlinks) or part of no specific exercise (and therefore in a separate package) which has to called manually? While the first way is much easier to do, there are two downsides: I'm not sure how good symlinks work with git in a cross-platform manner (it's fine on *nix) and copies of the same class are shitty as hell, if we don't have symlinks. On the other hand, the second approach requires clean and understandable documentation because it might require a more complex setup -- this has to be checked out later.
- Where do we track and store the input/output data (e.g. JSON/XML files) and how can we ensure that access to them is possible during the tests?

**Comment by N0W0RK** [comment]
I would try to use symlinks, I will test those on my Win/Linux/MacOS Machines and tell you my results.

**Comment by N0W0RK** [comment]
* So I created a [test repository](https://github.com/N0W0RK/Symlink_Test) to check symlink compatibiliy. As far as I can tell Windows symlinks work on Unix but not vice versa.
 * I also checked for native suport of fileformats like XML, YAML, JSON in Java and as far as I can tell, only XML is supported natively.

**Comment by CrsiX** [comment]
- But this means that it would work when created on a Windows machine, doesn't it? So, the creator of the test cases needs to be on a Windows machine to make it work? (Sigh)
- Well, then I assume we use some kind of XML data structure for that purpose?

**Comment by N0W0RK** [comment]
* We only need to create the symlinks once. I have a dualboot setup so this is less of an issue.
 * That would be the initial ide.

**Comment by CrsiX** [comment]
- Indeed. Well, then that's okay of course. Even though it might be required on a per-task basis, but that should be fine, too.
- Okay. Next two questions:
  - Do we want to have one centralized data storage for *all* tasks, one data storage on a per-task basis or one data storage on a per-case basis? The first variant is quite ugly because it requires lots of efforts to keep it clean and has no benefits. The second approach could be fine, but has the limitation that the structure of the XML file can't be well-defined (i.e. different test cases may require very different test input and output data formats), which is only an issue if we desire a well-defined format (something like a XML scheme). The last approach seems to be suiting our purpose best, doesn't it?
  - Where to actually store those data files? I don't know for sure, but it seems ugly to me to store them next to the `.java` files, especially since you usually have the `src` directory (which is called `tests` in our case) for the program source code only. What about a `data` directory that mirrors parts of the test case stucture (e.g. `tests/binarysearch/*.java` and `data/binarysearch/*.xml` for the GAD 2 task)?

**Comment by N0W0RK** [comment]
* I would suggest one XML per test group. IE in GAD 6 one file for Quicksort, one for DualPivotQuicksort etc. with filenames akin to those of the java files. So the `QuicksortTester.java` gets ist data from the `QuicksortInputs.xml` or sth along those lines.
 * The only issue I have is thet If we actually want to properly structure the data, we need to create 2 symbolic links per project. We could write a script for this but I am not sure if that is the best approach.

**Comment by CrsiX** [comment]
- Fine, then we agree on that. Since the XML files need to contain input and output data (as well as anything else related, e.g. logging), the data filename should equal the class name with `.xml` appended, e.g. `QuicksortTester.java` uses `QuicksortTester.xml`. But if that's somehow ugly, `QuicksortData.xml` would of course work, too.
- Hmm, true. In my opinion, two symlinks are still in the range to be okay. I definitively would avoid the script method, since it's incredibly error-prone. I just thought about a way to avoid the second symlink, but I don't have any confirmed working (TM) ideas. Something that could work would be using the absolute paths to calculate where the data files should usually reside (example below). That would certainly work with Java, but the cross-platform compatibility needs to be tested first.

Example (using a shell and your [test repo](https://github.com/N0W0RK/Symlink_Test)):

```sh
$ pwd
/home/user/Symlink_Test
$ cd Ubuntu/Folder
$ pwd
/home/user/Symlink_Test/Ubuntu/Folder
$ pwd -P
/home/user/Symlink_Test/Target_Folder
```

Here, you get the real path -- in our example the data file then would be stored in `../../binarysearch/`, wouldn't it?

**Comment by CrsiX** [comment]
Reasoning behind this step:
While most of the exercises had similar test structures and would therefore allow to create a unified, generalized test class theoretically, it has proven to be much easier to use specialized tests for every exercise. This will be done this way in the near future, too.
